lib/ex_blog_web/router.ex
defmodule ExBlogWeb.Router do
  use ExBlogWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :auth do
   plug ExBlog.Accounts.Pipeline
  end
  pipeline :ensure_auth do
   plug Guardian.Plug.EnsureAuthenticated
  end

  scope "/", ExBlogWeb do
    pipe_through [:browser, :auth]

    get "/", PageController, :index
    get "/signin", UserController, :new
    post "/signin", UserController, :create
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete
  end

  scope "/", ExBlogWeb do
    pipe_through [:browser, :auth, :ensure_auth]
    resources "/users", UserController, except: [:new, :create]
    resources "/articles", ArticleController
  end

  # Other scopes may use custom stacks.
  # scope "/api", ExBlogWeb do
  #   pipe_through :api
  # end
end

lib/ex_blog_web/views/layout_view.ex
defmodule ExBlogWeb.LayoutView do
  use ExBlogWeb, :view
  alias ExBlog.Accounts.Guardian
  def current_user(conn) do
    Guardian.Plug.current_resource(conn)
  end
end

lib/ex_blog_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>ExBlog · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>

 <body style="margin-top: 0px">
    <header class="header">
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container d-flex justify-content-between">
          <nav role="navigation">
            <ul class="nav nav-pills pull-right">
              <%= if current_user(@conn) do %>
                <li>
                  <%= link to: Routes.user_path(@conn, :show, current_user(@conn)) do %>
                    <button type="button" class="btn btn-default btn-sm">
                      Name: <b><%= current_user(@conn).name %></b>
                    </button>
                  <% end %>
                </li>
                <li>
                  <%= link to: Routes.session_path(@conn, :delete), method: :delete do %>
                    <button type="button" class="btn btn-default btn-sm">
                      Logout
                    </button>
                  <% end %>
                </li>
              <% else %>
                <li>
                  <%= link to: Routes.session_path(@conn, :new) do %>
                    <button type="button" class="btn btn-default btn-sm">
                      Login
                    </button>
                  <% end %>
                </li>
              <% end %>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <div class= "container">
      <p class="alert alert-success" role="alert"><%= get_flash(@conn, :success) %></p>
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>